-- PUMP Exercise Database Seed
-- Run this with: npx.cmd prisma db execute --file prisma/seed.sql --schema prisma/schema.prisma

DELETE FROM "Exercise";

INSERT INTO "Exercise" ("id", "nameEn", "nameHe", "descriptionHe", "muscleGroups", "workoutTypes", "difficulty", "equipment", "createdAt", "updatedAt") VALUES

-- PUSH EXERCISES (30)
(gen_random_uuid(), 'Barbell Bench Press', 'לחיצת חזה עם משקולת', 'תרגיל בסיסי לחיזוק שרירי החזה כתפיים וטריצפס', ARRAY['Chest','Triceps','Shoulders'], ARRAY['Push','Upper'], 'Intermediate', ARRAY['Barbell','Bench'], NOW(), NOW()),
(gen_random_uuid(), 'Dumbbell Bench Press', 'לחיצת חזה עם משקולות יד', 'לחיצה עם משקולות יד עם טווח תנועה גדול יותר', ARRAY['Chest','Triceps','Shoulders'], ARRAY['Push','Upper'], 'Intermediate', ARRAY['Dumbbells','Bench'], NOW(), NOW()),
(gen_random_uuid(), 'Incline Barbell Press', 'לchיצה משופעת', 'לחיצה על ספסל משופע להדגשת חזה עליון', ARRAY['Upper Chest','Shoulders','Triceps'], ARRAY['Push','Upper'], 'Intermediate', ARRAY['Barbell','Incline Bench'], NOW(), NOW()),
(gen_random_uuid(), 'Push-ups', 'שכיבות סמיכה', 'תרגיל משקל גוף קלאסי לחיזוק החזה', ARRAY['Chest','Triceps','Shoulders','Core'], ARRAY['Push','Upper','Full Body'], 'Beginner', ARRAY['Bodyweight'], NOW(), NOW()),
(gen_random_uuid(), 'Dips', 'מקבילים', 'תרגיל מצוין לטריצפס וחזה תחתון', ARRAY['Triceps','Lower Chest','Shoulders'], ARRAY['Push','Upper'], 'Intermediate', ARRAY['Parallel Bars'], NOW(), NOW()),
(gen_random_uuid(), 'Overhead Press', 'לחיצת כתפיים עומדת', 'לחיצה מעל הראש לחיזוק הכתפיים', ARRAY['Shoulders','Triceps','Upper Chest'], ARRAY['Push','Upper'], 'Intermediate', ARRAY['Barbell'], NOW(), NOW()),
(gen_random_uuid(), 'Dumbbell Shoulder Press', 'לחיצת כתפיים עם משקולות יד', 'לחיצה מעל הראש עם משקולות יד', ARRAY['Shoulders','Triceps'], ARRAY['Push','Upper'], 'Beginner', ARRAY['Dumbbells'], NOW(), NOW()),
(gen_random_uuid(), 'Lateral Raises', 'הרמות צד', 'הרמת משקולות יד לצדדים לבניית כתפיים רחבות', ARRAY['Side Shoulders'], ARRAY['Push','Upper'], 'Beginner', ARRAY['Dumbbells'], NOW(), NOW()),
(gen_random_uuid(), 'Front Raises', 'הרמות קדמיות', 'הרמת משקולות קדימה לחיזוק החלק הקדמי של הכתף', ARRAY['Front Shoulders'], ARRAY['Push','Upper'], 'Beginner', ARRAY['Dumbbells'], NOW(), NOW()),
(gen_random_uuid(), 'Tricep Pushdowns', 'לחיצות טריצפס בכבל', 'תרגיל בידוד לטריצפס באמצעות מכונת כבלים', ARRAY['Triceps'], ARRAY['Push','Upper'], 'Beginner', ARRAY['Cable Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Skull Crushers', 'מוחצי גולגולת', 'תרגיל טריצפס בשכיבה הורדת משקולת לכיוון המצח', ARRAY['Triceps'], ARRAY['Push','Upper'], 'Intermediate', ARRAY['Barbell','Bench'], NOW(), NOW()),
(gen_random_uuid(), 'Close-Grip Bench Press', 'לחיצת חזה צרה', 'לחיצת חזה עם אחיזה צרה להדגשת הטריצפס', ARRAY['Triceps','Inner Chest'], ARRAY['Push','Upper'], 'Intermediate', ARRAY['Barbell','Bench'], NOW(), NOW()),
(gen_random_uuid(), 'Cable Flyes', 'פתיחות בכבל', 'תרגיל בידוד לחזה באמצעות כבלים', ARRAY['Chest'], ARRAY['Push','Upper'], 'Intermediate', ARRAY['Cable Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Dumbbell Flyes', 'פתיחות עם משקולות יד', 'תרגיל בידוד לחזה עם מתיחה', ARRAY['Chest'], ARRAY['Push','Upper'], 'Intermediate', ARRAY['Dumbbells','Bench'], NOW(), NOW()),
(gen_random_uuid(), 'Arnold Press', 'לחיצת ארנולד', 'וריאציה של לחיצת כתפיים עם סיבוב', ARRAY['Shoulders','Triceps'], ARRAY['Push','Upper'], 'Advanced', ARRAY['Dumbbells'], NOW(), NOW()),
(gen_random_uuid(), 'Reverse Flyes', 'פתיחות הפוכות', 'תרגיל לכתפיים אחוריות מבוצע בנטייה', ARRAY['Rear Shoulders','Upper Back'], ARRAY['Push','Pull','Upper'], 'Beginner', ARRAY['Dumbbells'], NOW(), NOW()),
(gen_random_uuid(), 'Face Pulls', 'משיכות לפנים', 'תרגיל לכתפיים אחוריות באמצעות כבל', ARRAY['Rear Shoulders','Upper Back'], ARRAY['Pull','Upper'], 'Beginner', ARRAY['Cable Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Decline Bench Press', 'לחיצה משופעת למטה', 'לחיצה על ספסל משופע למטה להדגשת החזה התחתון', ARRAY['Lower Chest','Triceps'], ARRAY['Push','Upper'], 'Intermediate', ARRAY['Barbell','Decline Bench'], NOW(), NOW()),
(gen_random_uuid(), 'Diamond Push-ups', 'שכיבות סמיכה יהלום', 'וריאציה של שכיבות סמיכה עם ידיים קרובות', ARRAY['Triceps','Chest'], ARRAY['Push','Upper'], 'Intermediate', ARRAY['Bodyweight'], NOW(), NOW()),
(gen_random_uuid(), 'Pike Push-ups', 'שכיבות סמיכה פייק', 'וריאציה עם גוף מקופל להדגשת הכתפיים', ARRAY['Shoulders','Upper Chest'], ARRAY['Push','Upper'], 'Intermediate', ARRAY['Bodyweight'], NOW(), NOW()),
(gen_random_uuid(), 'Landmine Press', 'לחיצת לנדמיין', 'לחיצה זוויתית עם משקולת מעוגנת לרצפה', ARRAY['Shoulders','Upper Chest','Core'], ARRAY['Push','Upper'], 'Advanced', ARRAY['Barbell','Landmine'], NOW(), NOW()),
(gen_random_uuid(), 'Chest Dips', 'מקבילים לחזה', 'מקבילים עם נטייה קדימה להדגשת החזה', ARRAY['Lower Chest','Triceps'], ARRAY['Push','Upper'], 'Intermediate', ARRAY['Parallel Bars'], NOW(), NOW()),
(gen_random_uuid(), 'Incline Dumbbell Flyes', 'פתיחות משופעות', 'פתיחות על ספסל משופע לחזה עליון', ARRAY['Upper Chest'], ARRAY['Push','Upper'], 'Intermediate', ARRAY['Dumbbells','Incline Bench'], NOW(), NOW()),
(gen_random_uuid(), 'Overhead Tricep Extension', 'הרחבת טריצפס מעל הראש', 'תרגיל טריצפס עם משקולת מעל הראש', ARRAY['Triceps'], ARRAY['Push','Upper'], 'Beginner', ARRAY['Dumbbell'], NOW(), NOW()),
(gen_random_uuid(), 'Cable Crossovers', 'צלבים בכבל', 'תרגיל כבלים לחזה ממקומות שונים', ARRAY['Chest'], ARRAY['Push','Upper'], 'Intermediate', ARRAY['Cable Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Machine Chest Press', 'לחיצת חזה במכונה', 'לחיצת חזה במכונה בטוחה למתחילים', ARRAY['Chest','Triceps','Shoulders'], ARRAY['Push','Upper'], 'Beginner', ARRAY['Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Svend Press', 'לחיצת סוונד', 'לחיצה עם דיסק בין שתי הידיים', ARRAY['Inner Chest','Shoulders'], ARRAY['Push','Upper'], 'Beginner', ARRAY['Weight Plate'], NOW(), NOW()),
(gen_random_uuid(), 'Upright Rows', 'חתירה זקופה', 'משיכה של משקולת לעבר הסנטר', ARRAY['Shoulders','Traps'], ARRAY['Push','Pull','Upper'], 'Intermediate', ARRAY['Barbell'], NOW(), NOW()),
(gen_random_uuid(), 'Shoulder Shrugs', 'משיכת כתפיים', 'הרמת כתפיים לחיזוק שרירי המלכודות', ARRAY['Traps'], ARRAY['Push','Pull','Upper'], 'Beginner', ARRAY['Dumbbells'], NOW(), NOW()),
(gen_random_uuid(), 'Pec Deck', 'מכונת פתיחות חזה', 'תרגיל בידוד לחזה במכונה', ARRAY['Chest'], ARRAY['Push','Upper'], 'Beginner', ARRAY['Machine'], NOW(), NOW()),

-- PULL EXERCISES (30)
(gen_random_uuid(), 'Pull-ups', 'מתחים', 'תרגיל משקל גוף קלאסי לחיזוק הגב והביצפס', ARRAY['Lats','Biceps','Upper Back'], ARRAY['Pull','Upper','Full Body'], 'Intermediate', ARRAY['Pull-up Bar'], NOW(), NOW()),
(gen_random_uuid(), 'Chin-ups', 'מתחים הפוכים', 'מתחים עם אחיזה הפוכה להדגשת הביצפס', ARRAY['Biceps','Lats'], ARRAY['Pull','Upper'], 'Intermediate', ARRAY['Pull-up Bar'], NOW(), NOW()),
(gen_random_uuid(), 'Barbell Row', 'חתירה עם משקולת', 'חתירה בנטייה תרגיל בסיסי לגב', ARRAY['Lats','Mid Back','Traps'], ARRAY['Pull','Upper','Full Body'], 'Intermediate', ARRAY['Barbell'], NOW(), NOW()),
(gen_random_uuid(), 'Dumbbell Row', 'חתירה עם משקולת יד', 'חתירה חד-צדדית להתמקדות בכל צד בנפרד', ARRAY['Lats','Mid Back'], ARRAY['Pull','Upper'], 'Beginner', ARRAY['Dumbbell'], NOW(), NOW()),
(gen_random_uuid(), 'T-Bar Row', 'חתירת T-בר', 'חתירה עם מכשיר T-bar למתיחה מלאה של הגב', ARRAY['Lats','Mid Back','Traps'], ARRAY['Pull','Upper'], 'Intermediate', ARRAY['T-Bar Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Lat Pulldown', 'משיכה רחבה', 'משיכת כבל לכיוון החזה חלופה למתחים', ARRAY['Lats','Biceps'], ARRAY['Pull','Upper'], 'Beginner', ARRAY['Cable Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Seated Cable Row', 'חתירה בכבל בישיבה', 'חתירה בישיבה עם כבלים לחיזוק אמצע הגב', ARRAY['Mid Back','Lats','Biceps'], ARRAY['Pull','Upper'], 'Beginner', ARRAY['Cable Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Deadlift', 'הרמה מתה', 'תרגיל מורכב לכל הגוף מדגיש גב תחתון ורגליים', ARRAY['Lower Back','Glutes','Hamstrings','Traps'], ARRAY['Pull','Leg','Full Body'], 'Advanced', ARRAY['Barbell'], NOW(), NOW()),
(gen_random_uuid(), 'Romanian Deadlift', 'הרמה רומנית', 'וריאציה עם רגליים כמעט ישרות להדגשת הירכיים האחוריים', ARRAY['Hamstrings','Glutes','Lower Back'], ARRAY['Pull','Leg'], 'Intermediate', ARRAY['Barbell'], NOW(), NOW()),
(gen_random_uuid(), 'Barbell Curl', 'כיפוף ביצפס עם משקולת', 'תרגיל בידוד קלאסי לביצפס', ARRAY['Biceps'], ARRAY['Pull','Upper'], 'Beginner', ARRAY['Barbell'], NOW(), NOW()),
(gen_random_uuid(), 'Dumbbell Curl', 'כיפוף ביצפס עם משקולות יד', 'כיפוף ביצפס עם משקולות מאפשר טווח תנועה טבעי', ARRAY['Biceps'], ARRAY['Pull','Upper'], 'Beginner', ARRAY['Dumbbells'], NOW(), NOW()),
(gen_random_uuid(), 'Hammer Curl', 'כיפוף פטיש', 'כיפוף עם אחיזה ניטרלית לחיזוק הביצפס והזרוע', ARRAY['Biceps','Forearms'], ARRAY['Pull','Upper'], 'Beginner', ARRAY['Dumbbells'], NOW(), NOW()),
(gen_random_uuid(), 'Preacher Curl', 'כיפוף על ספסל סקוט', 'כיפוף ביצפס על ספסל תמיכה למניעת רמאות', ARRAY['Biceps'], ARRAY['Pull','Upper'], 'Beginner', ARRAY['Barbell','Preacher Bench'], NOW(), NOW()),
(gen_random_uuid(), 'Cable Bicep Curl', 'כיפוף ביצפס בכbל', 'כיפוף ביצפס עם כבל למתח מתמיד', ARRAY['Biceps'], ARRAY['Pull','Upper'], 'Beginner', ARRAY['Cable Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Inverted Row', 'חתירה הפוכה', 'חתירה עם משקל גוף תחת מוט', ARRAY['Mid Back','Lats','Biceps'], ARRAY['Pull','Upper'], 'Beginner', ARRAY['Barbell','Rack'], NOW(), NOW()),
(gen_random_uuid(), 'Pendlay Row', 'חתירת פנדליי', 'חתירה עם משקולת מהרצפה בכל חזרה', ARRAY['Lats','Mid Back','Traps'], ARRAY['Pull','Upper'], 'Advanced', ARRAY['Barbell'], NOW(), NOW()),
(gen_random_uuid(), 'Single-Arm Dumbbell Row', 'חתירה חד-צדדית', 'חתירה עם משקולת יד אחת בכל פעם', ARRAY['Lats','Mid Back'], ARRAY['Pull','Upper'], 'Beginner', ARRAY['Dumbbell','Bench'], NOW(), NOW()),
(gen_random_uuid(), 'Meadows Row', 'חתירת מידוז', 'חתירה ממוקדת עם משקולת מזווית מיוחדת', ARRAY['Lats','Mid Back'], ARRAY['Pull','Upper'], 'Advanced', ARRAY['Barbell'], NOW(), NOW()),
(gen_random_uuid(), 'Rack Pulls', 'משיכות מנקודה גבוהה', 'הרמה מתה מנקודת התחלה גבוהה יותר', ARRAY['Upper Back','Traps','Lower Back'], ARRAY['Pull','Upper'], 'Intermediate', ARRAY['Barbell','Rack'], NOW(), NOW()),
(gen_random_uuid(), 'Chest-Supported Row', 'חתירה עם תמיכת חזה', 'חתירה על ספסל משופע להסרת עומס מהגב התחתון', ARRAY['Mid Back','Lats'], ARRAY['Pull','Upper'], 'Beginner', ARRAY['Dumbbells','Incline Bench'], NOW(), NOW()),
(gen_random_uuid(), 'Wide-Grip Pulldown', 'משיכה רחבה', 'משיכה עם אחיזה רחבה להדגשת רוחב הגב', ARRAY['Lats'], ARRAY['Pull','Upper'], 'Beginner', ARRAY['Cable Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Close-Grip Pulldown', 'משיכה באחיזה צרה', 'משיכה עם אחיזה צרה להדגשת עובי הגב', ARRAY['Lats','Mid Back'], ARRAY['Pull','Upper'], 'Beginner', ARRAY['Cable Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Straight-Arm Pulldown', 'משיכה עם ידיים ישרות', 'משיכה עם ידיים ישרות לבידוד הלאטים', ARRAY['Lats'], ARRAY['Pull','Upper'], 'Intermediate', ARRAY['Cable Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Concentration Curl', 'כיפוף ריכוז', 'כיפוף ביצפס בישיבה עם מיקוד על שריר אחד', ARRAY['Biceps'], ARRAY['Pull','Upper'], 'Beginner', ARRAY['Dumbbell'], NOW(), NOW()),
(gen_random_uuid(), 'Spider Curl', 'כיפוף עכביש', 'כיפוף ביצפס על ספסל משופע למעלה', ARRAY['Biceps'], ARRAY['Pull','Upper'], 'Intermediate', ARRAY['Barbell','Incline Bench'], NOW(), NOW()),
(gen_random_uuid(), 'Reverse Curl', 'כיפוף הפוך', 'כיפוף עם אחיזה הפוכה לזרועות וביצפס', ARRAY['Forearms','Biceps'], ARRAY['Pull','Upper'], 'Beginner', ARRAY['Barbell'], NOW(), NOW()),
(gen_random_uuid(), 'Wrist Curl', 'כיפוף פרק כף יד', 'תרגיל לחיזוק הזרועות', ARRAY['Forearms'], ARRAY['Pull','Upper'], 'Beginner', ARRAY['Dumbbell'], NOW(), NOW()),
(gen_random_uuid(), 'Farmer Walk', 'הליכת חקלאי', 'הליכה עם משקולות כבדות לחיזוק אחיזה וליבה', ARRAY['Forearms','Traps','Core'], ARRAY['Pull','Full Body'], 'Intermediate', ARRAY['Dumbbells'], NOW(), NOW()),
(gen_random_uuid(), 'Cable Face Pull', 'משיכת פנים בכבל', 'משיכה לכיוון הפנים לכתפיים אחוריות', ARRAY['Rear Shoulders','Upper Back'], ARRAY['Pull','Upper'], 'Beginner', ARRAY['Cable Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Machine Row', 'חתירה במכונה', 'חתירה במכונה למתchילים', ARRAY['Mid Back','Lats'], ARRAY['Pull','Upper'], 'Beginner', ARRAY['Machine'], NOW(), NOW()),

-- LEG EXERCISES (25)
(gen_random_uuid(), 'Back Squat', 'סקוואט אחורי', 'תרגיל מורכב בסיסי לרגליים משקולת על הגב העליון', ARRAY['Quads','Glutes','Hamstrings'], ARRAY['Leg','Full Body'], 'Intermediate', ARRAY['Barbell','Rack'], NOW(), NOW()),
(gen_random_uuid(), 'Front Squat', 'סקוואט קדמי', 'סקוואט עם משקולת על החזה הקדמי', ARRAY['Quads','Core'], ARRAY['Leg','Full Body'], 'Advanced', ARRAY['Barbell','Rack'], NOW(), NOW()),
(gen_random_uuid(), 'Bulgarian Split Squat', 'סקוואט בולגרי', 'סקוואט חד-צדדי עם רגל אחורית מורמת', ARRAY['Quads','Glutes'], ARRAY['Leg'], 'Intermediate', ARRAY['Dumbbells','Bench'], NOW(), NOW()),
(gen_random_uuid(), 'Leg Press', 'לחיצת רגליים', 'לחיצת רגליים במכונה בטוחה וחזקה', ARRAY['Quads','Glutes','Hamstrings'], ARRAY['Leg'], 'Beginner', ARRAY['Leg Press Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Hack Squat', 'האק סקוואט', 'סקוואט במכונה זווית להדגשת הקוודים', ARRAY['Quads'], ARRAY['Leg'], 'Intermediate', ARRAY['Hack Squat Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Leg Extension', 'הרחבת רגליים', 'תרגיל בידוד לקוודריצפס', ARRAY['Quads'], ARRAY['Leg'], 'Beginner', ARRAY['Leg Extension Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Leg Curl', 'כיפוף רגליים', 'תרגיל בידוד לשרירי הירכיים האחוריים', ARRAY['Hamstrings'], ARRAY['Leg'], 'Beginner', ARRAY['Leg Curl Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Stiff-Leg Deadlift', 'הרמה עם רגליים נוקשות', 'דומה לרומנית אך עם רגליים יותר ישרות', ARRAY['Hamstrings','Lower Back'], ARRAY['Pull','Leg'], 'Intermediate', ARRAY['Barbell'], NOW(), NOW()),
(gen_random_uuid(), 'Lunges', 'צעדות', 'צעדים קדימה או אחורה לחיזוק הרגליים', ARRAY['Quads','Glutes'], ARRAY['Leg'], 'Beginner', ARRAY['Dumbbells'], NOW(), NOW()),
(gen_random_uuid(), 'Walking Lunges', 'צעדות הליכה', 'צעדות בתנועה קדימה', ARRAY['Quads','Glutes'], ARRAY['Leg'], 'Intermediate', ARRAY['Dumbbells'], NOW(), NOW()),
(gen_random_uuid(), 'Goblet Squat', 'סקוואט גביע', 'סקוואט עם משקולת יד אחת מול החזה', ARRAY['Quads','Glutes'], ARRAY['Leg'], 'Beginner', ARRAY['Dumbbell'], NOW(), NOW()),
(gen_random_uuid(), 'Sumo Squat', 'סקוואט סומו', 'סקוואט עם רגליים רחבות להדגשת הירכיים הפנימיים', ARRAY['Quads','Glutes','Inner Thighs'], ARRAY['Leg'], 'Beginner', ARRAY['Dumbbell'], NOW(), NOW()),
(gen_random_uuid(), 'Calf Raise', 'עליות שוקיים', 'עליה על קצות האצבעות לחיזוק השוקיים', ARRAY['Calves'], ARRAY['Leg'], 'Beginner', ARRAY['Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Seated Calf Raise', 'עליות שוקיים בישיבה', 'עליות שוקיים בישיבה להדגשת חלק אחר של השוק', ARRAY['Calves'], ARRAY['Leg'], 'Beginner', ARRAY['Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Hip Thrust', 'דחיפת ירכיים', 'דחיפת ירכיים למעלה על ספסל לחיזוק הישבן', ARRAY['Glutes','Hamstrings'], ARRAY['Leg','Lower'], 'Intermediate', ARRAY['Barbell','Bench'], NOW(), NOW()),
(gen_random_uuid(), 'Glute Bridge', 'גשר ישבן', 'הרמת ירכיים מהרצפה לחיזוק הישבן', ARRAY['Glutes','Hamstrings'], ARRAY['Leg','Lower'], 'Beginner', ARRAY['Bodyweight'], NOW(), NOW()),
(gen_random_uuid(), 'Step-Ups', 'עליות על קופסה', 'עליה על קופסה או ספסל', ARRAY['Quads','Glutes'], ARRAY['Leg'], 'Beginner', ARRAY['Box','Dumbbells'], NOW(), NOW()),
(gen_random_uuid(), 'Box Squat', 'סקוואט קופסה', 'סקוואט עם ישיבה על קופסה', ARRAY['Quads','Glutes'], ARRAY['Leg'], 'Intermediate', ARRAY['Barbell','Box'], NOW(), NOW()),
(gen_random_uuid(), 'Pistol Squat', 'סקוואט אקדח', 'סקוואט על רגל אחת מתקדם מאוד', ARRAY['Quads','Glutes'], ARRAY['Leg'], 'Advanced', ARRAY['Bodyweight'], NOW(), NOW()),
(gen_random_uuid(), 'Sissy Squat', 'סקוואט סיסי', 'סקוואט עם נטייה אחורה להדגשת הקוודים', ARRAY['Quads'], ARRAY['Leg'], 'Advanced', ARRAY['Bodyweight'], NOW(), NOW()),
(gen_random_uuid(), 'Nordic Curl', 'כיפוף נורדי', 'תרגיל לשרירי הירכיים האחוריים עם משקל גוף', ARRAY['Hamstrings'], ARRAY['Leg'], 'Advanced', ARRAY['Partner'], NOW(), NOW()),
(gen_random_uuid(), 'Good Mornings', 'בוקר טוב', 'נטייה קדימה עם משקולת על הכתפיים', ARRAY['Hamstrings','Lower Back','Glutes'], ARRAY['Leg','Pull'], 'Intermediate', ARRAY['Barbell'], NOW(), NOW()),
(gen_random_uuid(), 'Adductor Machine', 'מכונת קירוב רגליים', 'מכונה לחיזוק השרירים הפנימיים של הירך', ARRAY['Inner Thighs'], ARRAY['Leg'], 'Beginner', ARRAY['Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Abductor Machine', 'מכונת ריחוק רגליים', 'מכונה לחיזוק השרירים החיצוניים של הירך', ARRAY['Outer Thighs','Glutes'], ARRAY['Leg'], 'Beginner', ARRAY['Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Wall Sit', 'ישיבת קיר', 'החזקה סטטית בתנוחת ישיבה על הקיר', ARRAY['Quads','Glutes'], ARRAY['Leg'], 'Beginner', ARRAY['Bodyweight'], NOW(), NOW()),

-- CORE EXERCISES (15)
(gen_random_uuid(), 'Plank', 'פלאנק', 'תרגיל סטטי לחיזוק הליבה', ARRAY['Core','Abs'], ARRAY['Core','Full Body'], 'Beginner', ARRAY['Bodyweight'], NOW(), NOW()),
(gen_random_uuid(), 'Crunches', 'כפיפות בטן', 'תרגיל קלאסי לשרירי הבטן העליונים', ARRAY['Abs'], ARRAY['Core'], 'Beginner', ARRAY['Bodyweight'], NOW(), NOW()),
(gen_random_uuid(), 'Russian Twists', 'סיבובים רוסיים', 'סיבוב מצד לצד לחיזוק האלכסונים', ARRAY['Obliques','Abs'], ARRAY['Core'], 'Beginner', ARRAY['Weight Plate'], NOW(), NOW()),
(gen_random_uuid(), 'Leg Raises', 'הרמות רגליים', 'הרמת רגליים לחיזוק הבטן התחתונה', ARRAY['Lower Abs'], ARRAY['Core'], 'Intermediate', ARRAY['Bodyweight'], NOW(), NOW()),
(gen_random_uuid(), 'Hanging Leg Raises', 'הרמות רגליים תלויות', 'הרמת רגליים בתלייה מוט', ARRAY['Lower Abs','Hip Flexors'], ARRAY['Core'], 'Advanced', ARRAY['Pull-up Bar'], NOW(), NOW()),
(gen_random_uuid(), 'Cable Crunches', 'כפיפות בטן בכבל', 'כפיפות בטן עם התנגדות כבל', ARRAY['Abs'], ARRAY['Core'], 'Intermediate', ARRAY['Cable Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Ab Wheel Rollout', 'גלגלת בטן', 'גלילה עם גלגל בטן לחיזוק ליבה', ARRAY['Abs','Core'], ARRAY['Core'], 'Advanced', ARRAY['Ab Wheel'], NOW(), NOW()),
(gen_random_uuid(), 'Mountain Climbers', 'מטפסי הרים', 'תרגיל דינמי לליבה וקרדיו', ARRAY['Core','Abs'], ARRAY['Core','Full Body'], 'Intermediate', ARRAY['Bodyweight'], NOW(), NOW()),
(gen_random_uuid(), 'Bicycle Crunches', 'כפיפות אופניים', 'כפיפות בטן עם תנועת רגליים כמו רכיבה על אופניים', ARRAY['Abs','Obliques'], ARRAY['Core'], 'Beginner', ARRAY['Bodyweight'], NOW(), NOW()),
(gen_random_uuid(), 'Side Plank', 'פלאנק צד', 'פלאנק על צד אחד לחיזוק האלכסונים', ARRAY['Obliques','Core'], ARRAY['Core'], 'Intermediate', ARRAY['Bodyweight'], NOW(), NOW()),
(gen_random_uuid(), 'Hollow Hold', 'החזקת חלל', 'החזקת הגוף בצורת חלל לחיזוק ליבה', ARRAY['Abs','Core'], ARRAY['Core'], 'Advanced', ARRAY['Bodyweight'], NOW(), NOW()),
(gen_random_uuid(), 'Dead Bug', 'חרק מת', 'תרגיל ליבה בשכיבה עם תנועות מבוקרות', ARRAY['Core','Abs'], ARRAY['Core'], 'Beginner', ARRAY['Bodyweight'], NOW(), NOW()),
(gen_random_uuid(), 'Pallof Press', 'לחיצת פאלוף', 'תרגיל אנטי-רוטציה עם כבל', ARRAY['Core','Obliques'], ARRAY['Core'], 'Intermediate', ARRAY['Cable Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Wood Choppers', 'כריתת עצים', 'תנועת חיתוך אלכסונית עם כבל', ARRAY['Obliques','Core'], ARRAY['Core'], 'Intermediate', ARRAY['Cable Machine'], NOW(), NOW()),
(gen_random_uuid(), 'Bird Dog', 'כלב ציפור', 'תרגיל שיווי משקל ויציבות ליבה', ARRAY['Core','Lower Back'], ARRAY['Core'], 'Beginner', ARRAY['Bodyweight'], NOW(), NOW());

SELECT COUNT(*) AS total_exercises FROM "Exercise";
