name: Sync to Azure DevOps

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history
      
      - name: Push to Azure DevOps
        env:
          AZURE_DEVOPS_URL: ${{ secrets.AZURE_DEVOPS_URL }}
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          git remote add azure https://$AZURE_DEVOPS_PAT@dev.azure.com/yboaz/Pump/_git/Pump
          git push azure main --force
